### ISSUE TITLE
Schnorr stuff is based on old secp256k1

### ISSUE THREAD

**Issue by ysangkok** [prolic/secp256k1-schnorr#1]
As you can see from [the PR](https://github.com/haskoin/secp256k1-haskell/pull/26), the schnorr bindings were made against the BIP340 spec as it was around March 2020. The spec and implementation were since changed, some symbols probably have different names, that's why you got linking errors. To make it work, you should diff the commit mentioned in the PR with the upstream secp256k1 that you want this library to target. Then you can know how to adjust the bindings.

**Comment by ysangkok** [comment]
Ensure that you don't have an old version of libsecp256k1 laying around. I don't wanna investigate more, since I don't work in cryptocurrency any more and I think it is already a disproportionate part of the Haskell ecosystem.

**Comment by prolic** [comment]
This is not for some cryptocurrency shitcoin. Anyway, thanks for your hints @ysangkok.
